version: '2'

services:
    operations:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      working_dir: /data/web/
      ports:
        - "5001:5001"
      volumes:
        - .:/data/web/
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        ZK_HOSTS: 192.168.5.30:2181,192.168.5.30:2182,192.168.5.30:2183
        ZK_PATH: /platform/operation_dq2
        ZK_AUTH: wangqq:123456
